#############################################################################
# Makefile for building: tst_canmsgdecode_test
# Generated by qmake (2.01a) (Qt 4.8.4) on: Tue Apr 2 16:41:21 2013
# Project:  CANmsgDecode_Test.pro
# Template: app
# Command: /usr/bin/qmake -o tst_canmsgdecode_test.xcodeproj/project.pbxproj CANmsgDecode_Test.pro
#############################################################################

MOC       = /Developer/Tools/Qt/moc
UIC       = /Developer/Tools/Qt/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DSRCDIR=\"/Users/jorgeb500/Documents/Programing/Senior Design/canusbV1/trunk/CAN_GUI/Sunseeker_CAN_GUI/CANmsgDecode//\" -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_SHARED
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-xcode -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtTest.framework/Versions/4/Headers -I/usr/include/QtTest -I/usr/include -I../../Sunseeker_CAN_GUI -I. -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers -F/Library/Frameworks
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./moc_canmsgdecode.cpp ./tst_canmsgdecode_test.moc
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_canmsgdecode.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_canmsgdecode.cpp
moc_canmsgdecode.cpp: canmsgdecode.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ canmsgdecode.h -o moc_canmsgdecode.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: tst_canmsgdecode_test.moc
compiler_moc_source_clean:
	-$(DEL_FILE) tst_canmsgdecode_test.moc
tst_canmsgdecode_test.moc: canmsgdecode.h \
		tst_canmsgdecode_test.cpp
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ tst_canmsgdecode_test.cpp -o tst_canmsgdecode_test.moc

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean 

